language: php

notifications:
  email:
    on_success: never

php:
  - 7.3
  - 7.4

matrix:
  fast_finish: true
  include:
    # Linux Instances
    - os: linux
      dist: xenial
    # Windows Instances
    - os: windows
      language: sh

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - vendor/bin/phpunit
