#https://github.com/reactphp/event-loop/blob/master/.travis.yml
language: php

# lock distro so new future defaults will not break the build
dist: xenial

matrix:
  fast_finish: true
  include:
    # Linux Instances
    - php: 7.2
    - php: 7.3
    - php: 7.4
    # Windows Instances
    - name: "Windows"
      os: windows
      language: shell # no built-in php support
      before_install:
        - choco install php
        - choco install composer
        - export PATH="$(powershell -Command '("Process", "Machine" | % { [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", "" } | Select -Unique | % { cygpath $_ }) -Join ":"')"
      install:
        - composer install

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - vendor/bin/phpunit
